### ISSUE TITLE
Allow setting DynamoDB client

### ISSUE THREAD

**Issue by hassankhan** [automategreen/dynamoose#261] opened 2017-12-09 14:42 UTC
It would be cool if we could pass our own DynamoDB service client object. This is so we could use DAX, which requires a specially instantiated version of the regular client.

This could be something like a `client` property in the `Model` options.

**Comment by brandongoode** [comment] 2018-01-02 22:50
I'm open to it.  #212

**Comment by fishcharlie** [comment] 2018-03-10 18:33
Closing as a duplicate of #212

**Closed by fishcharlie** 2018-03-10 18:33 UTC

**Comment by fishcharlie** [comment] 2018-04-03 22:53
I created a PR for this (#330). I need some help writing some tests, improving the documentation with an example, and testing it with DAX (since I have never used DAX before). If anyone would like to help please follow the instructions on that PR.
