### ISSUE TITLE
Adding attribute (or new key) to nested map fails (for unknown only?)

### ISSUE THREAD

**Issue by stang-tgs** [automategreen/dynamoose#253] opened 2017-12-05 20:56 UTC
I want to add a new key/val pair to an existing nested map.  How would I do this?  The nested map's Schema is not defined, since the key names are dynamic, so "saveUnknown" must be used.

When I attempt to do an update, the entire nested map is not saved/updated.  See example below.  A room contains users "apple and banana".  I want to add "cherry".

What is the expected behaviour, and how am I to accomplish what I'm attempting?

```javascript
const dynamoose = require('dynamoose');

const awsConfig = {
    region: 'us-west-2',
    //    sslEnabled: false,
    endpoint: 'http://localhost:8000'
};

dynamoose.local();

dynamoose.AWS.config.update(awsConfig);

const schema = new dynamoose.Schema({
    _id: {
        type: String, //guild id
        hashKey: true
    },
    aMap : {
        aKey : String
    }
}, {saveUnknown: true, useDocumentTypes: true});

const Room = dynamoose.model('Room', schema);
let room = new Room(
    {
        _id: 'myRoom',
        aMap: {
            aKey: 'valforkey',
            undefKey: 'valForUnknown'
        },
        users: {
            apple: {name: 'apple', score: 10},
            banana: {name: 'banana', score: 20}
        }
    });
room.save().then((thing) => {
    console.log('thing:' + JSON.stringify(thing));
    //thing:{"_id":"myRoom","aMap":{"aKey":"valforkey"},"users":{"apple":{"name":"apple","score":10},"banana":{"name":"banana","score":20}}}
    return Room.update({_id : 'myRoom'}, {users:{cherry: {name: 'cherry', score: 30}}});
})
    .then((thing) => {
        console.log('2nd thing: ' + JSON.stringify(thing));
        //2nd thing: {"_id":"myRoom","aMap":{"aKey":"valforkey"},"users":{}}
    });
```

**Comment by brandongoode** [comment] 2018-01-02 22:31
@stang-tgs - Are you still having this issue?  Does it work when not in local mode? 

Sorry for not replying earlier.

**Comment by fishcharlie** [comment] 2018-03-31 16:27
Closing due to no reply. @stang-tgs please let us know if you are still having this issue and we can try to help further.

**Closed by fishcharlie** 2018-03-31 16:27 UTC

**Comment by whilesoftware** [comment] 2018-06-01 20:28
@brandongoode i can confirm that it does not work in real AWS mode or in local mode.
