### ISSUE TITLE
"Missing region in config" when using dynamoose.local()

### ISSUE THREAD

**Issue by danduh** [automategreen/dynamoose#251] opened 2017-12-04 18:45 UTC
Hi, 
When using 
```
const dynamoose = require('dynamoose');
dynamoose.local();
const createModel = new SomeModel({
    userSub: '24234234eeeee',
    type: 'absPrice'
});
createModel.save(function (err) {
    if (err) {
        return console.log(err);
    }
    console.log('Ta-da!');
});

```

I'm getting an error: 
```
ConfigError: Missing region in config
```

Thanks

**Comment by jacintoArias** [comment] 2017-12-05 16:44
Have you tried declaring the configuration despite using `dynamoose.local()`? Its seems to be required in order to load the package even if local mode is not using it.

try adding the configuration:
```
const dynamoose = require('dynamoose');
dynamoose.AWS.config.update({
  region: 'eu-west-1',
});
dynamoose.local();
```

**Comment by jacintoArias** [comment] 2017-12-05 16:53
Its seems to be the expected behaviour in `aws-sdk` aws/aws-sdk-js#880. By default it creates different database files for each region (unless specified)

Shall we close this one then?

**Comment by YevheniiHerasymchuk** [comment] 2017-12-08 16:35
Adding the configuration above didn't help.

**Comment by jacintoArias** [comment] 2017-12-08 18:10
This error typically comes from the `aws-sdk`. 

It looks for local config and credentials files (typically on `~/.aws`), have you ever configured aws with the cli?

The sdk requires a region, but also a username and credentials... The are used as well in dynamodb local as it emulates both users and regions.

Is it still asking for the region configuration?, Can you share the full error trace?

**Comment by YevheniiHerasymchuk** [comment] 2017-12-11 09:33
Seems like fixed it. 
Configured both in env variables and in project files.

**Closed** 2018-01-02 22:25 UTC

**Comment by naeemark** [comment] 2018-08-02 04:48
See the accepted answer: https://stackoverflow.com/questions/37259824/user-pools-for-amazon-cognito-credentialserror-missing-credentials-in-config
