### ISSUE TITLE
Feature Request - Exponential Backoff

### ISSUE THREAD

**Issue by lengk** [automategreen/dynamoose#312] opened 2018-03-12 13:16 UTC
When receiving the exception "ProvisionedThroughputExceededException"

[There is a recommended way of handling it by AWS](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) using the Exponential Backoff method. 

It would be great if the .save() or batchOperations could do this automatically?

**Comment by fishcharlie** [comment] 2018-03-12 14:33
Closing as a duplicate of #209. If you'd like to submit a PR to get this implemented that'd be awesome!

**Closed by fishcharlie** 2018-03-12 14:33 UTC
