### ISSUE TITLE
Regex support for map

### ISSUE THREAD

**Issue by ngosala** [automategreen/dynamoose#103] opened 2017-01-19 17:49 UTC
is there a regex support for map ? something like 

attrib1: {
  type:'map',
  map: {
    "REGEX": { // should match arbitary keys
        type: 'list',
        list:[
        A: {type:String},
        B: {type: String}
       ]
    }
 }
}

should match 

attrib1{
  "hello": [
    {
    "A": "123",
    "B": "abc"
    }
   ],
  "hi": [
    {
    "A": "456",
    "B": "xyz"
    }
   ]
}

**Comment by brandongoode** [comment] 2017-01-19 18:46
A while back @benjcooley had done some work on it and sent PR #21.  I overlooked it (entirely my fault), and it never got merged.  Now it needs some work to resolve the conflicts with newer changes.  The problem is finding the time to resolve the conflicts.

**Comment by ngosala** [comment] 2017-01-19 19:00
Ahh... yes I just saw the PR #21. I will be watching this space for updates. Thanks for quick reply.

**Closed** 2017-02-01 15:20 UTC
