### ISSUE TITLE
Scan is missing many of my items

### ISSUE THREAD

**Issue by fcheong3b** [automategreen/dynamoose#349] opened 2018-04-23 20:20 UTC
Hi, I'm running scan operation on one of my tables but it is missing many of my items. I'm running a scan on the createdTime timestamp filed. But there are many items that are not coming in the request even when I keep calling till no lastIndex field is set. it doesn't matter the time of windows they are never returned. my table maybe has less than 5k items.
this is an example of my query:

```
async getJobsByDate (date, att) {
    try {
      date = date || new Date(moment().format('YYYY/MM/DD')).getTime()
      console.log(date)
      let jobs = await new Promise((resolve, reject) => {
        let query = this.model.scan('creationDate').ge(date)
        if (att && !_.isEmpty(att) && _.isArray(att)) {
          query.attributes(att)
        }
        query.exec((err, results) => {
          if (err) { reject(err) }
          resolve(results)
        })
      })
      while (jobs && jobs.lastKey) {
        let moreData = await new Promise((resolve, reject) => {
          let query = this.model.scan('creationDate').ge(date).startAt(jobs.lastKey)
          if (att && !_.isEmpty(att) && _.isArray(att)) {
            query.attributes(att)
          }
          query.exec((err, jobs) => {
            if (err) { reject(err) }
            resolve(jobs)
          })
        })
        jobs.pop() // removing lastKey value
        jobs = jobs.concat(moreData)
      }
      console.log('job found')
      console.log(jobs)
      return jobs
    } catch (error) {
      console.error('getJobs Error->', error.message)
    }
  }
```
I'm using clientId as hasKey y jobId has rangeKey, no using any Index GSI so far.

**Comment by fishcharlie** [comment] 2018-04-23 20:53
@fcheong3b After looking at your code very briefly it looks decent. Can you provide a reproducible example so I can test this?

You could also try to use [`scan.consistent()`](https://dynamoosejs.com/api#scanconsistent) to see if that helps or instead of manually looking for the `lastKey` use [`scan.all()`](https://dynamoosejs.com/api#scanalldelay-max).

**Comment by fcheong3b** [comment] 2018-04-23 21:54
Thank for the answer I will try the scan.consistency() method. Can I combine scan.all() with some filters or do I have to run the filter on the app side?

**Comment by fishcharlie** [comment] 2018-04-23 21:57
@fcheong3b You can run `scan.all()` with filters. If you use filters you shouldn't need to do any processing on the app side unless you want to do more complicated filters that Dynamoose/DynamoDB doesn't support.

Let me know if that works for you or if it doesn't work for you.

**Comment by fcheong3b** [comment] 2018-04-23 22:50
Hi, I just refactor my code to use all what you advice but I'm getting an error
```
async getJobsByDate (date, att) {
    try {
      date = date || new Date(moment().format('YYYY/MM/DD')).getTime()
      let jobs = await new Promise((resolve, reject) => {
        let filter = {
          'creationDate': {
            ge: date
          }
        }
        let query = this.model.scan(filter).all()
        if (att && !_.isEmpty(att) && _.isArray(att)) {
          query.attributes(att)
        }
        query.consistency().exec((err, results) => {
          if (err) { reject(err) }
          resolve(results)
        })
      })
      return jobs
    } catch (error) {
      console.error('getAllItemsFromDate Error->', error.message)
    }
  }
```
But I'm gettting this `Error-> _this8.model.scan(...).all is not a function`

**Comment by fishcharlie** [comment] 2018-04-23 23:02
You can run a scan on a schema.

**Comment by fcheong3b** [comment] 2018-04-23 23:30
@fishcharlie Thank you for your comments, the error above was made by the version of dynamoose I was using (0.7.0) now I update it to the latest (0.8.7) and the function above is working ok. About the amout of data Still need to test it on my porduction environment but I hope will be ok.

**Comment by fishcharlie** [comment] 2018-04-24 00:55
@fcheong3b Awesome. I'm going to close this issue now. Please comment if you run into any more problems. Good luck!

**Closed by fishcharlie** 2018-04-24 00:55 UTC

**Comment by CalvinMcstein** [comment] 2018-06-06 00:17
@fishcharlie I am running the latest 0.8.7 and trying to use **consistent read**. 

Please advise if this is right:

myModel.query('customerType').eq('hni')
		        .filter('criteria').eq('high')
			.consistency()
			.exec(function (err, record) {
                          // process further
			})

This returns "myModel.query(...).eq(...).consistency is not a function"

**Comment by fishcharlie** [comment] 2018-06-06 00:58
@CalvinMcstein As I mentioned in a previous comment you must use the `[Query.consistent()](https://dynamoosejs.com/api#queryconsistent)` function. Looks like you are using `consistency` instead of `consistent`.

**Comment by CalvinMcstein** [comment] 2018-06-07 04:41
@fishcharlie I tried `consistent` but doesn't return records...

I wonder if my model definition has something to do with it -- captured the definition and my query here https://gist.github.com/CalvinMcstein/904a23719acb50da21c3d7df31d018b0

Thanks for your help!

**Comment by CalvinMcstein** [comment] 2018-06-07 04:45
Ah! `ValidationException: Consistent reads are not supported on global secondary indexes`

**Comment by fishcharlie** [comment] 2018-06-07 14:06
That error explains it. I’d maybe do some research about if there is a workaround or how other systems handle that limitation if you really need consistent reads.
