### ISSUE TITLE
how to parse JSON object to model

### ISSUE THREAD

**Issue by aAmitSengar** [automategreen/dynamoose#238] opened 2017-11-21 14:55 UTC
actually i'm just trying to parse less data from json and want to save in db.
`  var myModel = new UserModel(UserObject)`

but after this there is no change in the myModel it's same as UserObject

**Comment by brandongoode** [comment] 2017-11-27 12:57
I'm not following the question. Could you write a runnable example?   Thanks

**Comment by aAmitSengar** [comment] 2017-12-14 13:41
> //Model

```
var dynamoose = require('dynamoose')
var Schema = dynamoose.Schema
IssuesSchema= = new Schema({
  id : {
    type : String,
    hashKey : true
  },
  issuesId: {
    type: Number
  }
});
module.exports = IssuesSchema
```

> //End Model
> //Use of Model

```
var UserObject=/*JsonData get from somewhere else*/
var myModel = new UserModel(UserObject)
myModel.save() //Error : save is not a function
```

**Comment by fishcharlie** [comment] 2018-03-11 18:49
@aAmitSengar Is the only error `save is not a function`? I can't reproduce this, so could you maybe provide a full example project so I can debug the error?

The only thing that stands out to me as the issue is you have an extra `)` at the end of your require statement `var myissue= require('models/issues-model.js')) `

**Comment by fishcharlie** [comment] 2018-04-09 17:34
Closing this issue due to no reply from the OP. Please comment if this is still an issue and we can look at it further.

**Closed by fishcharlie** 2018-04-09 17:34 UTC
