### ISSUE TITLE
How to initialize dynamoose?

### ISSUE THREAD

**Issue by spitfyr86** [automategreen/dynamoose#218] opened 2017-10-24 09:10 UTC
I'm trying to connect to a local dynamoDB in my machine but I always get the error, "ConfigError: Missing region in config."
By the way, I'm using Typescipt in my Node.js app.

**Comment by brandongoode** [comment] 2017-10-25 10:44
Try setting your env variable for the region (even though it's not really needed for local).
```sh
export AWS_REGION="us-east-1"
```

**Comment by jacintoArias** [comment] 2017-12-05 16:54
Its seems to be the expected behaviour in `aws-sdk` aws/aws-sdk-js#880. By default it creates different database files for each region (unless specified)

Shall we close this one then?

**Closed** 2017-12-06 03:20 UTC

**Comment by spitfyr86** [comment] 2017-12-06 03:32
I didn't have time to resolve this. I'll get back on this if I can.
