### ISSUE TITLE
List of Maps in schema

### ISSUE THREAD

**Issue by Raphael-R-R** [automategreen/dynamoose#255] opened 2017-12-07 07:10 UTC
Hey there,

I have in my DynamoDB database a table containing an element as a List of Maps. Each Map item does not have any specific structure.

I've tried to describe it like this:

```js
const schema = new dynamoose.Schema({
  Id: {
    type: String,
    hashKey: true,
    required: true
  },
  Name: {
    type: String,
    required: true
  },
  Content: {
    type: 'list',
    list: [Map]
  }
},
{
  useNativeBooleans: true,
  useDocumentTypes: true,
  saveUnknown: true
})
```

However, every item in Content equals to {}. I am able to retrieve the data when changing `list: [Map]` to `list: [String]`, but I would like to have it in Json not in a string containing DynamoDB Json format.

How can I do that?

**Comment by Onnion** [comment] 2017-12-07 17:51
I have the same issue, but in my case is a little different, my map have specific structure.
_CacheSearch Schema_
```javascript
const fares = {
    money: Number,
    points: Number,
    fare:Number,
    boarding: Number
}

const price = {
    type: String,
    adult: fares,
    child: fares,
    baby: fares,
    boarding: Number,
    modality: String,
    baggage_type: String,
    modality_name:String,
    id:String,
    boarding: Number,
    search_type_match:String
}

const connection = {
    code: String,
    departure_airport: String,
    arrival_airport: String,
    departure_date: String,
    arrival_date: String,
    duration: Number,
    waiting: Number
}

const flight = {
    code: String,
    departure_airport: String,
    arrival_airport: String,
    departure_date: String,
    arrival_date: String,
    boarding_tax: Number,
    duration: Number,
    connections: [connection],
    prices: [price]
}

const search = {
    company: String,
    origin_airport: String,
    destination_airport: String,
    departure_date: Date,
    return_date: Date,
    type_trip: String,
    type_fare: String,
    modality: String,
    adults: Number,
    children: Number,
    babies: Number,
    start_date: String,
    finish_date: String,
    timeout: Boolean,
    duration: Number,
    updated_at: String,
    created_at: String
}

const CacheSearch = new dynamoose.Schema({
    .
    .
    .
    search: search,
    flights: [flight],
    flights_back: [flight]
}, { useDocumentTypes: true, useNativeBooleans: true });

```

**Problem**

Before save, i log the type of prices attribute and i get 'object', but in response of save i get 'string':

```javascript
 console.log(typeof cache.flights[0].prices[0]);
        cache.save().then((result) => {
                console.log(typeof result.flights[0].prices[0]);
                resolve(result);
            })
            .catch((err) => {                
                reject(err);
            });
```

```console
>object
>string
```
In the aws console:
```javascript
//hide the values
"prices": [
        "{\"adult\":{\"\":0,\"points\":0,\"fare\":0,\"boarding\":0},\"child\":{\"money\":0,\"points\":0,\"fare\":0,\"boarding\":0},\"baby\":{\"money\":0,\"points\":0,\"fare\":0,\"boarding\":0},\"id\":\"\",\"type\":\"\",\"modality\":\"\",\"modality_name\":\"\",\"boarding\":0,\"search_type_match\":null,\"baggage_type\":\"\"}",
       ...
      ]
```

But the attribute 'connections' save normal, type Map in aws console

**Comment by Raphael-R-R** [comment] 2017-12-08 09:25
I've noticed that it is working when replacing Map to Object. However, it only works when creating new items from the Dynamoose API. It stores every item as a String in the database

The invert happens if the object is created from the DynamoDB console

**Comment by brandongoode** [comment] 2018-01-02 22:38
@Raphael-R-R - Are you still having this issue? Try the master branch to see if the problem is fixed.  There were several fixes related to this that hasn't been released yet.

**Comment by fishcharlie** [comment] 2018-03-31 16:27
Closing due to no reply. Please let us know if you are still having this issue and we can try to help further.

**Closed by fishcharlie** 2018-03-31 16:27 UTC
